Web/Mihaylov.Web/Controllers/GalleryController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OutputCaching;
using Microsoft.Extensions.Logging;
using Mihaylov.Api.Other.Client;
using Mihaylov.Web.Areas;

namespace Mihaylov.Web.Controllers
{
    public class GalleryController : Controller
    {
        private readonly ILogger _logger;
        private readonly IOtherApiClient _client;

        public GalleryController(ILoggerFactory loggerFactory, IOtherApiClient client)
        {
            _logger = loggerFactory.CreateLogger(this.GetType());
            _client = client;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            _client.AddToken(Request.GetToken());
            IEnumerable<AlbumModel> images = await _client.GalleryImagesAsync().ConfigureAwait(false);

            return View(images);
        }

        [HttpGet]
        [OutputCache(Duration = 3600, VaryByRouteValueNames = new[] { "id" })]
        public async Task<IActionResult> Thumbnail(string id)
        {
            _client.AddToken(Request.GetToken());
            FileResponse image = await _client.GalleryThumbnailAsync(id).ConfigureAwait(false);
            if (image == null || image.Stream == null || image.StatusCode != 200)
            {
                return NotFound();
            }

            return File(image.Stream, "image/jpeg");
        }
    }
}

Web/Mihaylov.Web/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using Mihaylov.Api.Site.Contracts.Helpers;
using Mihaylov.Api.Site.Contracts.Helpers.Models;
using Mihaylov.Common.Generic.Servises.Interfaces;
using Mihaylov.Common.Host.Authorization;
using Mihaylov.Web.Hubs;
using Mihaylov.Web.Models;
using Mihaylov.Web.Models.Configs;

namespace Mihaylov.Web.Controllers
{
    [JwtAuthorize(Roles = UserConstants.AdminRole)]
    public class MediaController : Controller
    {
        private readonly IMediaService _mediaService;
        private readonly IFileWrapper _file;
        private readonly IProgressReporterFactory _progressReporter;
        private readonly IMemoryCache _cache;
        private readonly MediaConfig _config;

        private readonly string _reportPath;
        private readonly string _sortReportPath;

        public MediaController(IMediaService mediaService, IFileWrapper fileWrapper,
            IProgressReporterFactory progressReporter, IMemoryCache cache, IOptions<MediaConfig> settings)
        {
            _mediaService = mediaService;
            _file = fileWrapper;
            _progressReporter = progressReporter;
            _cache = cache;

            _reportPath = $"{_mediaService.GetBasePath()}/response.json";
            _sortReportPath = $"{_mediaService.GetBasePath()}/sortResponse.json";
            _config = settings.Value;
        }

        [HttpGet]
        public IActionResult Duplicates()
        {
            var model = _mediaService.GetReportData<DuplicateResponse>(_reportPath, null);

            var duplicates = model.Duplicates
                                 //.Where(d => d.List.Any(f => !f.IsImage))                                 
                                 .Select(d => new DuplicateModel()
                                 {
                                     Checksum = d.Checksum,
                                     Hash = d.Hash,
                                     Similarity = d.Similarity,
                                     List = d.List.Where(f => _file.GetFileInfo(f.FullPath).Exists),
                                     Count = d.Count
                                 })
                                 .Where(d => d.List.Count() > 1)
                                 .ToList();

            return View(new DuplicatesViewModel()
            {
                FilesCount = model.FileCount,
                DuplicatesCount = duplicates.Count,
                Duplicates = duplicates.Take(2),
                RedirectUrl = nameof(Duplicates)
            });
        }

        [HttpGet]
        public IActionResult Sort(int? page)
        {
            int pageSize = 8;
            int columnCount = 4;

            var model = _mediaService.GetReportData<SortResponse>(_sortReportPath, null);
            var files = model.Files.Where(f => _file.GetFileInfo(f.FullPath).Exists).ToList();

            var directories = _file.GetDirectories(_config.SoftPath);

            var picsOnPage = columnCount * pageSize;
            var maxPageCount = files.Count / picsOnPage;
            if (files.Count % picsOnPage > 0)
            {
                maxPageCount++;
            }

            if (page <= 0)
            {
                return Redirect(nameof(Sort));
            }

            if (page >= maxPageCount && maxPageCount > 0)
            {
                return Redirect($"Sort?page={maxPageCount - 1}");
            }

            if (!page.HasValue)
            {
                page = 0;
            }

            return View(new SortViewModel()
            {
                Page = page.Value,
                PageCount = maxPageCount,
                FilesCount = files.Count,
                LastProcessed = model.LastProcessed,
                Files = Convert(files, columnCount).Skip(page.Value * pageSize).Take(pageSize),
                Dirs = directories,
                RedirectUrl = nameof(Sort)
            });
        }

        [HttpGet]
        public IActionResult GetThumbnail(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!_cache.TryGetValue(id, out byte[] bytes))
            {
                var path = WebUtility.UrlDecode(id);
                bytes = _mediaService.GetThumbnail(path, 200);

                _cache.Set(id, bytes, TimeSpan.FromMinutes(60));
            }

            if (bytes?.Any() != true)
            {
                return NotFound();
            }

            return File(bytes, "image/png");
        }

        [HttpGet]
        public IActionResult DeleteFile(string id, string redirectUrl)
        {
            var path = WebUtility.UrlDecode(id);

            _file.DeleteFile(path);

            return RedirectToAction(redirectUrl);
        }

        [HttpGet]
        public IActionResult DeleteFileById(Guid id, string redirectUrl)
        {
            var filesModel = _mediaService.GetReportData<SortResponse>(_sortReportPath, null);
            var path = filesModel.Files.Where(f => f.FileId == id).Select(f => f.FullPath).FirstOrDefault();

            _file.DeleteFile(path);

            return RedirectToAction(redirectUrl);
        }

        [HttpGet]
        public IActionResult ReadFiles(string connectionId)
        {
            var progressReporter = _progressReporter.GetLoadingBarReporter(connectionId, "updateLoadingBar");

            var files = new List<MediaInfoModel>();

            if (!string.IsNullOrEmpty(_config.DuplicatePathLocked))
            {
                var lockedFiles = _mediaService.GetAllFiles(_config.DuplicatePathLocked, true, true, true, progressReporter.Report);
                files.AddRange(lockedFiles);
            }

            if (!string.IsNullOrEmpty(_config.DuplicatePathNotLocked))
            {
                var nonlockedFiles = _mediaService.GetAllFiles(_config.DuplicatePathNotLocked, true, false, true, progressReporter.Report);
                files.AddRange(nonlockedFiles);
            }

            //var allFiles = JsonSerializer.Serialize(files);
            //_file.SaveFile($"{_mediaService.GetBasePath()}/allFiles.json", allFiles);

            //var fileBytes = _file.ReadFile($"{_mediaService.GetBasePath()}/allFiles.json");
            //var files = JsonSerializer.Deserialize<List<MediaInfoModel>>(fileBytes);

            var content = _mediaService.GetDuplicates(files);
            var result = JsonSerializer.Serialize(content);
            _file.SaveFile(_reportPath, result);

            return Ok();
        }

        [HttpGet]
        public IActionResult ReadFilesSort(string connectionId)
        {
            var progressReporter = _progressReporter.GetLoadingBarReporter(connectionId, "updateLoadingBar");

            var files = _mediaService.GetAllFiles(_config.SoftPath, false, false, false, progressReporter.Report);

            var content = _mediaService.GetSorted(files);

            content.LastProcessed = new DateTime(2025, 03, 01);

            var result = JsonSerializer.Serialize(content);
            _file.SaveFile(_sortReportPath, result);

            return Ok();
        }

        [HttpPost]
        public IActionResult CreateDirectory([FromForm] string direcrotyName)
        {
            if (string.IsNullOrEmpty(direcrotyName))
            {
                return Redirect(nameof(Sort));
            }

            _file.CreateDirectory(_config.SoftPath, direcrotyName);
            return Redirect(nameof(Sort));
        }

        [HttpPost]
        public IActionResult MovePics([FromForm] MovePicsViewModel model)
        {
            if (model.Files != null && model.Files.Any() && !string.IsNullOrWhiteSpace(model.Dir))
            {
                var filesModel = _mediaService.GetReportData<SortResponse>(_sortReportPath, null);

                var fileNames = filesModel.Files.Where(f => model.Files.Contains(f.FileId))
                                                .Select(f => f.FullPath)
                                                .ToList();
                var dirPath = Path.Combine(_config.SoftPath, model.Dir);

                _file.MoveFiles(dirPath, fileNames);
            }

            return Redirect(nameof(Sort));
        }

        [HttpGet]
        public IActionResult RenamePics()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RenamePicsRun()
        {
            var directory = new DirectoryInfo(_config.RenamePath);
            if (directory.Exists)
            {
                var files = directory.GetFiles();
                if (files.Any())
                {
                    foreach (var file in files)
                    {
                        var fileNameParts = file.Name.Split('_', StringSplitOptions.RemoveEmptyEntries);
                        var filePrefix = fileNameParts[0].Substring(0, 3);
                        int number = int.Parse(fileNameParts[0].Substring(3));

                        var newFilePath = $"{file.DirectoryName}\\{filePrefix}{number + 1}_{fileNameParts[1]}";

                        System.IO.File.Move(file.FullName, newFilePath);
                    }
                }
            }

            return Redirect(nameof(RenamePics));
        }

        private IEnumerable<IEnumerable<MediaInfoModel>> Convert(IEnumerable<MediaInfoModel> list, int columnCount)
        {
            var result = new List<List<MediaInfoModel>>();

            if (!list.Any())
            {
                return result;
            }

            var count = 0;

            do
            {
                var row = new List<MediaInfoModel>();
                result.Add(row);

                for (int j = 0; j < columnCount; j++)
                {

Web/Mihaylov.Web/Controllers/NexusController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mihaylov.Api.Other.Client;
using Mihaylov.Common.Host.Authorization;
using Mihaylov.Web.Areas;
using Mihaylov.Web.Models.Nexus;

namespace Mihaylov.Web.Controllers
{
    [JwtAuthorize(Roles = UserConstants.AdminRole)]
    public class NexusController : Controller
    {
        private readonly ILogger _logger;
        private readonly IOtherApiClient _client;

        public NexusController(ILoggerFactory loggerFactory, IOtherApiClient client)
        {
            _logger = loggerFactory.CreateLogger(this.GetType());
            _client = client;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            _client.AddToken(Request.GetToken());
            NexusImages images = await _client.ImagesAsync().ConfigureAwait(false);
            NexusBlobs blobs = await _client.BlobsAsync().ConfigureAwait(false);

            var model = new NexusMainModel
            {
                Images = images,
                Blobs = blobs
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Clear()
        {
            _client.AddToken(Request.GetToken());

            await _client.ClearImagesAsync().ConfigureAwait(false);
            await _client.RunTasksAsync().ConfigureAwait(false);

            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Mihaylov.Web/Controllers/VeleroController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mihaylov.Api.Other.Client;
using Mihaylov.Common.Host.Authorization;
using Mihaylov.Web.Areas;
using Mihaylov.Web.Models.Velero;

namespace Mihaylov.Web.Controllers
{
    [JwtAuthorize(Roles = UserConstants.AdminRole)]
    public class VeleroController : Controller
    {
        private readonly ILogger _logger;
        private readonly IOtherApiClient _client;

        public VeleroController(ILoggerFactory loggerFactory, IOtherApiClient client)
        {
            _logger = loggerFactory.CreateLogger(this.GetType());
            _client = client;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            _client.AddToken(Request.GetToken());
            ScheduleResponse images = await _client.SchedulesAsync().ConfigureAwait(false);

            var veleroVersion = string.Empty;
            
            try
            {
                veleroVersion = await _client.ExeVersionAsync().ConfigureAwait(false);
            }
            catch (Exception)
            {
            }

            var dates = images.Schedules.SelectMany(s => s.Backups)
                                        .Where(b => b.CreatedOn.HasValue)
                                        .Select(b => b.CreatedOn.Value.Date)
                                        .Distinct()
                                        .OrderByDescending(d => d)
                                        .ToList();

            var model = new SchedulesMainModel
            {
                Statistics = images.Statistics,
                Schedules = images.Schedules.Select(s => new ScheduleViewModel(s)).ToList(),
                Dates = dates,
                VeleroVersion = veleroVersion,
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> CreateBackup(string schedule)
        {
            _client.AddToken(Request.GetToken());
            var request = new CreateBackupModel() { ScheduleName = schedule };
            await _client.CreateBackupAsync(request).ConfigureAwait(false);


            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteBackup(string backup)
        {
            _client.AddToken(Request.GetToken());
            await _client.DeleteBackupAsync(backup).ConfigureAwait(false);
            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Mihaylov.Web/Views/Shared/_Layout.cshtml
@using Mihaylov.Common.Host.Authorization;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mihaylov</title>
    <link rel="icon" href="~/img/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mihaylov.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Михайлов</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Index">Галерия</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Време</a>
                        </li>
                        @if (User.IsAdmin())
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Снимки</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Site" asp-action="Index">Сайт</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Media" asp-action="Duplicates">Дубликати</a>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Media" asp-action="Sort">Сортиране</a>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Media" asp-action="RenamePics">Преименуване</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Други</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Concert" asp-action="Index">Концерти</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Cluster" asp-action="Index">Клъстър</a>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Nexus" asp-action="Index">Nexus</a>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Velero" asp-action="Index">Velero</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid body-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - mihaylov-s.eu
            @if (User.IsAdmin())
            {
                <text>- </text>            
                <a asp-area="" asp-controller="Home" asp-action="ModuleInfo">Modules</a>
            }
        </div>
    </footer>

    <span class="serverUrl" data-url="@Context.Request.PathBase"></span>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/popperjs/core/dist/umd/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/main-layout.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>